### ISSUE TITLE
UnhandledPromiseRejectionWarning: HttpError: Bad credentials

### ISSUE THREAD

**Issue by u0324020** [toko-bifrost/ms-teams-deploy-card#38]
Workflow:
`    - uses: toko-bifrost/ms-teams-deploy-card@3.1.2
      if: always()
      with:
        github-token: ${{ secrets.GIT_TOKEN }}
        webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        environment: dev # won't be included in the card if none
        timezone: Asia/Taipei
        view-status-action-text: View in Actions
        review-diffs-action-text: Review Commit Diffs
`

Error:
`(node:145712) UnhandledPromiseRejectionWarning: HttpError: Bad credentials
19
    at /home/runner/actions-runner/_work/_actions/toko-bifrost/ms-teams-deploy-card/3.1.2/dist/main/index.js:1:462593
20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
21
    at async getOctokitCommit (/home/runner/actions-runner/_work/_actions/toko-bifrost/ms-teams-deploy-card/3.1.2/dist/main/index.js:1:36969)
22
    at async Object.formatAndNotify (/home/runner/actions-runner/_work/_actions/toko-bifrost/ms-teams-deploy-card/3.1.2/dist/main/index.js:1:37465)
23
(node:145712) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
24
(node:145712) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by rokeno** [comment]
i have the same thing. No idea if it's the msteams incoming webhook or the github token (which has been regenerated with full credentials)
