### ISSUE TITLE
Allow setting http_proxy variables

### ISSUE THREAD

**Issue by sousaaguilherme** [toko-bifrost/ms-teams-deploy-card#39]
Hi!

I'm using onpremises GitHub Enterprise Server with no direct connection to the internet, only through http proxy.

I've tried setting the env var "HTTP_PROXY" and "HTTPS_PROXY" in your action but with or without it I receive the following error:

`Run toko-bifrost/ms-teams-deploy-card@master
Workflow run information: {
  "owner": "BdP",
  "repo": "ml-cpi",
  "ref": "074c4c578f04a733227d30a2e0053dd34d0c2a1d",
  "branchUrl": "https://github.com/BdP/ml-cpi/tree/refs/heads/DEV",
  "runId": "398",
  "runNum": "28"
}
(node:1635192) UnhandledPromiseRejectionWarning: HttpError: request to https://api.github.com/repos/mc/ml-cpi/commits/074c4c578f04a733227d30a2e0053dd34d0c2a1d failed, reason: getaddrinfo ENOTFOUND api.github.com
    at /opt/actions-runner/_work/_actions/toko-bifrost/ms-teams-deploy-card/master/dist/main/index.js:1:463063
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getOctokitCommit (/opt/actions-runner/_work/_actions/toko-bifrost/ms-teams-deploy-card/master/dist/main/index.js:1:36969)
    at async Object.formatAndNotify (/opt/actions-runner/_work/_actions/toko-bifrost/ms-teams-deploy-card/master/dist/main/index.js:1:37465)
(node:1635192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1635192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code`

Would it be possible to take the env var into consideration? Or have an optional argument in your action?

Thanks :)

**Comment by sousaaguilherme** [comment]
Nevermind... just noticed now that the action actively assumes the repo is hosted on github.com so even if the connection was being established through the proxy it wouldn't find it... 😢 

It would be great though if it would be possible to customize the target github endpoint instead of assuming it's github.com

Best regards
