### ISSUE TITLE
UnhandledPromiseRejectionWarning: HttpError

### ISSUE THREAD

**Issue by liquidkey** [toko-bifrost/ms-teams-deploy-card#43]
Hi

I am getting the below error

(node:109) UnhandledPromiseRejectionWarning: HttpError: request to https://api.github.com/repos/GlobeOp/gopricingml/commits/4deb107c56f1419f0f849394dde9aa5ce7c87da1 failed, reason: connect ETIMEDOUT 140.82.112.6:443
    at /__w/_actions/toko-bifrost/ms-teams-deploy-card/master/dist/main/index.js:1:463063
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getOctokitCommit (/__w/_actions/toko-bifrost/ms-teams-deploy-card/master/dist/main/index.js:1:36969)
    at async Object.formatAndNotify (/__w/_actions/toko-bifrost/ms-teams-deploy-card/master/dist/main/index.js:1:37465)
(node:109) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:109) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dchourasia** [comment]
@liquidkey we are facing the same error where its is posting the start-card but not the exit-card and throwing this exception in stead... did you find any resolution to this issue

**Comment by stevie-** [comment]
> Hi
> 
> I am getting the below error
> 
> (node:109) UnhandledPromiseRejectionWarning: HttpError: request to https://api.github.com/repos/GlobeOp/gopricingml/commits/4deb107c56f1419f0f849394dde9aa5ce7c87da1 failed, reason: connect ETIMEDOUT 140.82.112.6:443 at /__w/_actions/toko-bifrost/ms-teams-deploy-card/master/dist/main/index.js:1:463063 at processTicksAndRejections (internal/process/task_queues.js:97:5) at async getOctokitCommit (/__w/_actions/toko-bifrost/ms-teams-deploy-card/master/dist/main/index.js:1:36969) at async Object.formatAndNotify (/__w/_actions/toko-bifrost/ms-teams-deploy-card/master/dist/main/index.js:1:37465) (node:109) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:109) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Seems like your runner can't connect to github api: 
```
reason: connect ETIMEDOUT 140.82.112.6:443
```

Another issue one may see here is a permissions error if you set permissions in your workflow.
This action requires
```
permissions:
 actions: read
```
